Fix regex in quote function
google/zx pull request #170
Opened 2021-07-28 19:30 UTC by PATROMO

Fixes #169

2021-07-28 19:35 UTC, PATROMO commented
@googlebot I signed it!

2021-07-28 19:37 UTC, antongolub commented
@PATROMO ,

Could you also add a `,` to the regex? This is also commonly used. For example, https://www.npmjs.com/package/depcheck
```
--ignores="eslint,babel-*".
```

2021-07-28 19:41 UTC, antongolub approved these changes

2021-08-04 12:27 UTC, liuyangc3 commented
I think args should also support base64 chars, it happens when passing some base64 based access_key in cmdline

2021-08-04 13:53 UTC, antonmedv requested changes

2021-08-10 10:40 UTC, closed without merging