Configurable / overridable log, default stderr
google/zx pull request #376
Opened 2022-04-05 00:15 UTC by JohnnyMarnell

Change feedback / logging statements to a `$.log()` function (instead of hardcoding `console.log()`, thus this could be overridden by scripts as well.
Default to stderr (so piping works / behaves like other CLI tools, even in verbose mode)
Add zx CLI arg `--log-stdout` to instead send to stdout, if desired

Fixes #375
https://github.com/google/zx/issues/375

- [ x ] Tests pass
- [ x ] Appropriate changes to README are included in PR
- [ x ] Types updated

2022-04-06 15:12 UTC, antongolub commented
Hmm... Maybe introduce more high-level logger instead?
Smth like:
```js
logger = ({vebose, level, message}) => {
   if (!verbose) {
      return
   }
   const print = level === 'error' ? console.error ? console.log
   print(...message)
}
```

2022-04-06 22:33 UTC, JohnnyMarnell commented
@antongolub Thanks for taking a look! First I want to make sure this isn't continually getting lost... the main problem is that zx is logging diagnostic info to stdout / `console.log`, and this snippet would have same problem (that is, all diagnostic logging including `'info'` level as well should be `console.error` / stderr). Otherwise, pipes will fail and writing to a file will not be consistent.

Please see the discussion and links in the linked issue for more context: https://github.com/google/zx/issues/375

2022-04-06 22:51 UTC, JohnnyMarnell commented
As for a more flexible logging mechanism, I'm fine with adding that (again if to stderr, and stdout is kept only for command output, and it has potential to be merged).

My preference would be to again align with shell / CLI tooling conventions, where we could use a standard verbose flag level like `-v`, `-vv`, `-vvv`, etc to distinguish a minimum log verbosity level of 1, 2, 3, ... etc (zero / falsey without any v arg).

So zx core, something like
```js
$.verbosityLevel = (process.argv.find(arg => arg.match(/^-v+$/)) || '-').length - 1
$.log = (level, ...msg) => $.verbosityLevel >= level && console.error(...msg)
```

and thus could write scripts like
```js
$.log(0, 'this is always logged')

$.log(1, 'verbosity level is at least 1, printing args', argv)

$.log(2, 'verbosity level is at least 2, thus will print commands [to stderr ofc ;) ]')
$.verbose = $.verbosityLevel >= 2
await $`echo hi`
```

2022-04-07 06:57 UTC, antonmedv commented
Verbosity levels are good idea. But first we need to figure out configuration for commands. 

Right now there is one config $.verbose for both: the command and the output. Both echoed to stdout. 

First we can change the command to stderr.

2022-04-08 12:07 UTC, JohnnyMarnell commented
Cool, I like where we're headed.

I agree allowing separate configuration for verbosity of 1.) echo-logging underlying command executions and 2.) doing that plus logging their outputs, would be a good thing.

Paired with supporting verbosity levels, one approach could be leave verbosity levels 0 and 1 up to the script writer, command echo defaults to 2, and command output to 3 (both overridable if desired).

So a simple `demo.mjs` script that looks like:
```js
$.log(0, 'Running demo (this is always logged):')
await $`for i in $(seq 1 3); do echo '{"json":{"val":'$i'}}' ; done`
$.log(1, 'Finished demo!')
```

When run with `-v` verbosity levels 0 thru 3 would look like these (and note, of course, pipes working :) ):
<img width="452" alt="zx-ss" src="https://user-images.githubusercontent.com/2214886/162431815-a04be36b-dbc8-4e76-ba0f-ca70214ddc08.png">

And the hack preamble I whipped up to achieve this and demonstrate how it could work:
```js
const originalZx = $
originalZx.verbose = false // disabling, probably replacing / deprecating
$ = (...args) => {
    if ($.verbosityLevel >= $.commandEchoVerbosityLevel) {
        const tokens = args.join(' ').split(' ')
        console.error('$', chalk.greenBright(tokens[0]), tokens.slice(1).join(' '))
    }
    return originalZx(...args).then(p => {
        console.log(p.stdout.trim())
        if ($.verbosityLevel >= $.commandOutputVerbosityLevel) {
            console.error(p.stdout.trim())
        }
    })
}

$.commandEchoVerbosityLevel = 2 // overridable via script
$.commandOutputVerbosityLevel = 3 // overridable via script
$.verbosityLevel = (process.argv.find(arg => arg.match(/^-v+$/)) || '-').length - 1
$.log = (level, ...msg) => $.verbosityLevel >= level && console.error(...msg)
```

2022-04-08 12:08 UTC, JohnnyMarnell commented
LMK how I can help / proceed

2022-04-08 12:29 UTC, antongolub commented
We're reinventing the wheel ))) Let's look at [debug](https://www.npmjs.com/package/debug)
```js
$.debug = '*' // '*,-not_http',  'http,cmd'
$.verbose = 'error' // 0, 1, 2, 3, 'log', 'debug', 'info'
```

2022-04-08 12:35 UTC, antonmedv commented
Let’s omit verbosity level for now.

2022-04-15 12:02 UTC, antonmedv requested changes

2022-04-15 12:02 UTC, antonmedv commented on zx.mjs
> +  $.log = argv['log-stdout'] ? (...args) => console.log(...args) : (...args) => console.error(...args)
Let's not introduce a new config function. Let's try to find out a better solution. Probably we can agree on what log of commands should always go to stderr.

2022-06-06 14:54 UTC, closed without merging